### ISSUE TITLE
Sparrow плагин yandex-disk

### ISSUE THREAD

**Issue by melezhik** [vrag86/perl-yandex-disk-api#2]
Здравствуйте! Я написал Sparrow плагин для доступа к Yandex диск через cli . Плагин  использует ваш модуль, если есть интерес - можно включить информацию о плагине в документацию.

https://sparrowhub.org/info/yandex-disk

**Comment by vrag86** [comment]
Добрый день.
Это плагины для какой-то CMS?
А в какую документацию включить, по модулю? В какую секцию?

10.11.2017 08:41, Alexey Melezhik пишет:

**Comment by melezhik** [comment]
Добрый день!

Это плагин для Sparrow , это не CMS, это scripting platform, не знаю как лучше перевести на русский. Sparrow позваляет загружать, устанавливать и запускать разнообразные пользователькие скрипты. Есть много статей о Sparrow, например можно посмотреть тут - https://habrahabr.ru/post/318604/ 

Я бы просто добавил секцию что-то типа CLI API и дал сслыку на данный плагин ... Но на ваше усмотрение ... Просто у вас сейчас только программный API, а данный плагин позволяет использовать yandex-disk с консоли, возможно другим будет интересно.

**Comment by vrag86** [comment]
Ок, добавлю
В данный момент пилю также модуль для Облака mail
Если будет интересно, можете потом добавить и для него плагин sparrow

10.11.2017 11:13, Alexey Melezhik пишет:

**Comment by melezhik** [comment]
Да, конечно. На самом деле, вы и сами можете написать плагин, это досточно просто - могу помочь если что ...

**Comment by melezhik** [comment]
Ссылка по теме - https://habrahabr.ru/post/342288/ , упомнят плагин yandex-disk . можете, если есть желание оставлять свои комментарии там.
