### ISSUE TITLE
BUFF_SIZE is too small

### ISSUE THREAD

**Issue by guligas** [vrag86/perl-yandex-disk-api#4]
Due to small BUFF_SIZE (only 81 byte), file upload goes very slowly. I raised it manually to 4096 and it works fine. Could you set BUFF_SIZE to 4096 bytes or there is a reason why BUFF_SIZE is so small?
https://github.com/vrag86/perl-yandex-disk-api/blob/ade3d38f2ca12329ac89f62e61eeeb63daaa9400/lib/Yandex/Disk.pm#L21

**Comment by vrag86** [comment]
Fixed
